package systemdesign.twitter;

/**
 * Created by ruili1 on 10/8/17.
 */

import java.util.*;

/**
 * Definition of Tweet (in Tweet.java):
 * public class Tweet {
 *     public int id;
 *     public int user_id;
 *     public String text;
 *     public static Tweet create(int user_id, String tweet_text) {
 *         // This will create a new tweet object,
 *         // and auto fill id
 *     }
 * }
 */

public class MiniTwitter {

    class TweetComparator implements Comparator<Tweet> {

        public int compare(Tweet o1, Tweet o2) {

            if(o1.id > o2.id) {
                return -1;
            }else if(o1.id == o2.id) {
                return 0;
            }else {
                return 1;
            }
        }
    }

    Map<Integer, List<Tweet>> map = null;
    Map<Integer, TreeSet<Integer>> followerMap = null;  // a-> {b, c} means a follows b and c (key is followers)

    public MiniTwitter() {

        map = new HashMap<Integer, List<Tweet>>();
        followerMap = new HashMap<Integer, TreeSet<Integer>>();
    }

    /*
     * @param user_id: An integer
     * @param tweet_text: a string
     * @return: a tweet
     */
    public Tweet postTweet(int user_id, String tweet_text) {

        Tweet tweet = Tweet.create(user_id, tweet_text);

        List<Tweet> tweets = new ArrayList<Tweet>();
        if(map.containsKey(user_id)){
            tweets = map.get(user_id);
        }
        tweets.add(tweet);
        map.put(user_id, tweets);

        return tweet;
    }

    /*
     * @param user_id: An integer
     * @return: a list of 10 new feeds recently and sort by timeline
     */
    public List<Tweet> getNewsFeed(int user_id) {

        List<Integer> users = getFollowers(user_id);

        List<Tweet> tweets = new ArrayList<Tweet>();

        // add its own tweets
        if(map.containsKey(user_id)) {
            tweets.addAll(map.get(user_id));
        }
        // add tweets of the users that it follows
        for(Integer user : users){
            tweets.addAll(getTimeline(user));
        }

        if(tweets.size() == 0){
            return tweets;
        }

        Collections.sort(tweets, new TweetComparator());
        int len = Math.min(tweets.size(), 10);
        return tweets.subList(0, len);
    }

    /*
     * @param user_id: An integer
     * @return: a list of 10 new posts recently and sort by timeline
     */
    public List<Tweet> getTimeline(int user_id) {

        if(map.containsKey(user_id)){
            List<Tweet> tweets = map.get(user_id);
            Collections.sort(tweets, new TweetComparator());
            int len = Math.min(tweets.size(), 10);
            return tweets.subList(0, len);
        }else{
            return new ArrayList<Tweet>();
        }
    }

    /*
     * @param from_user_id: An integer
     * @param to_user_id: An integer
     * @return: nothing
     */
    public void follow(int from_user_id, int to_user_id) {

        // update followerMap
        TreeSet<Integer> users = new TreeSet<Integer>();
        if(followerMap.containsKey(from_user_id)){
            users = followerMap.get(from_user_id);
        }
        users.add(to_user_id);
        followerMap.put(from_user_id, users);
    }

    /*
     * @param from_user_id: An integer
     * @param to_user_id: An integer
     * @return: nothing
     */
    public void unfollow(int from_user_id, int to_user_id) {

        if(followerMap.containsKey(from_user_id)){
            TreeSet<Integer> users = followerMap.get(from_user_id);
            users.remove(to_user_id);
            if(users.isEmpty()){
                followerMap.remove(from_user_id);
            }else{
                followerMap.put(from_user_id, users);
            }
        }
    }

    public List<Integer> getFollowers(int user_id) {

        if(followerMap.containsKey(user_id)) {
            return new ArrayList<Integer>(followerMap.get(user_id));
        }else{
            return new ArrayList<Integer>();
        }
    }

    public static void main(String[] args){

        MiniTwitter tweeter = new MiniTwitter();

//        System.out.println(tweeter.postTweet(1, "LintCode is Good!!!"));
//        System.out.println(tweeter.getNewsFeed(1));
//        System.out.println(tweeter.getTimeline(1));
//        tweeter.follow(2, 1);
//        tweeter.postTweet(1, "LintCode is best!!!");
//        System.out.println(tweeter.getNewsFeed(2));
//        tweeter.unfollow(2, 1);
//        System.out.println(tweeter.getNewsFeed(2));

        System.out.println(tweeter.postTweet(13, "cbdefghik"));
        System.out.println(tweeter.postTweet(14, "intco"));
        System.out.println(tweeter.postTweet(7, "eilovelin"));
        System.out.println(tweeter.postTweet(14, "elintcode"));
        tweeter.follow(13, 5);
        tweeter.follow(6, 15);
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.follow(9, 5);
        System.out.println(tweeter.postTweet(14, "velintc"));
        System.out.println(tweeter.postTweet(3, "esti love "));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.follow(16, 13);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(10, "e isbest"));
        tweeter.follow(15, 8);
        System.out.println(tweeter.postTweet(2, "cbdefgh"));
        System.out.println(tweeter.postTweet(9, "delintco"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(6, "elint"));
        System.out.println(tweeter.postTweet(9, "fghik"));
        System.out.println(tweeter.postTweet(16, "ntcodel"));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.postTweet(9, "ghikis"));
        tweeter.follow(4, 10);
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.postTweet(15, "defghikl"));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(11, "cbdefghikl"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(3));
        tweeter.follow(6, 7);
        tweeter.follow(15, 5);
        System.out.println(tweeter.postTweet(1, "lintcode"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getTimeline(6));
        tweeter.follow(10, 6);
        tweeter.follow(6, 14);
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(4, "tcodelint"));
        System.out.println(tweeter.getNewsFeed(5));
        tweeter.follow(13, 2);
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.postTweet(13, "ikisacb"));
        tweeter.follow(4, 9);
        System.out.println(tweeter.getTimeline(7));
        tweeter.follow(8, 12);
        tweeter.follow(1, 10);
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.unfollow(8, 12);
        System.out.println(tweeter.postTweet(12, "intcodea"));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(8, "ghikl"));
        tweeter.unfollow(15, 8); // tmp
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(5));
        tweeter.follow(16, 15);
        tweeter.follow(13, 12);
        tweeter.follow(4, 6);
        System.out.println(tweeter.postTweet(2, "bdefg"));
        tweeter.follow(9, 13);
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getTimeline(8));
        tweeter.follow(3, 15);
        System.out.println(tweeter.postTweet(8, "isbes"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(10, "ode isbe"));
        tweeter.follow(16, 7);
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(2));
        tweeter.follow(1, 14);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.postTweet(11, "code is"));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(8, "intcodeacb"));
        System.out.println(tweeter.postTweet(3, "velin"));
        tweeter.follow(14, 12);
        System.out.println(tweeter.postTweet(3, "hikbes"));
        System.out.println(tweeter.postTweet(4, "cbdef"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(16, "lintcode"));
        tweeter.follow(15, 8);
        tweeter.follow(10, 2);
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.postTweet(16, "code l"));
        tweeter.follow(9, 12);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.postTweet(7, "besti l"));
        tweeter.follow(7, 8);
        tweeter.follow(10, 8);
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(6, "deacbdefgh"));
        tweeter.follow(5, 9);
        tweeter.unfollow(10, 6);
        System.out.println(tweeter.postTweet(11, "hiklmnl"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(3, "ti lovelin"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getTimeline(3));
        tweeter.follow(3, 1);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.postTweet(7, "eacbdefghi"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(8, "codeilov"));
        System.out.println(tweeter.postTweet(12, "mnlin"));
        System.out.println(tweeter.postTweet(13, "lintcodea"));
        System.out.println(tweeter.postTweet(9, "bdefgh"));
        tweeter.follow(12, 13);
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(11, "lintco"));
        System.out.println(tweeter.postTweet(13, "codei"));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(2));
        tweeter.follow(2, 11);
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.follow(5, 15);
        System.out.println(tweeter.postTweet(13, "tcode "));
        tweeter.unfollow(6, 7);
        System.out.println(tweeter.postTweet(8, "ilovelint"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.postTweet(4, "lintcodel"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(12));
        tweeter.follow(16, 12);
        tweeter.follow(12, 14);
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(7, "tcode lin"));
        System.out.println(tweeter.postTweet(14, "lintcodel"));
        tweeter.follow(5, 4);
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(15, "odelintco"));
        System.out.println(tweeter.postTweet(7, "ntcod"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(2));
        tweeter.follow(6, 7);
        tweeter.unfollow(12, 14);
        tweeter.follow(3, 16);
        System.out.println(tweeter.postTweet(12, "intcode i"));
        System.out.println(tweeter.postTweet(4, "ikisacbde"));
        System.out.println(tweeter.postTweet(9, "acbdefg"));
        tweeter.follow(4, 13);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(1, "hiklmn"));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.postTweet(4, "ghikli"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(4, "cbdefghi"));
        System.out.println(tweeter.postTweet(3, "defghi"));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(3, "defgh"));
        tweeter.follow(1, 9);
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(13, "fghik"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.postTweet(13, "code i"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(6, "tcode"));
        tweeter.follow(15, 16);
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.postTweet(7, "ntcode"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(6, "tcode"));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(10, " love"));
        System.out.println(tweeter.postTweet(11, "ikbest"));
        tweeter.follow(11, 9);
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.follow(8, 10);
        System.out.println(tweeter.postTweet(5, "codel"));
        tweeter.unfollow(3, 15);
        System.out.println(tweeter.postTweet(15, "tcodeac"));
        System.out.println(tweeter.postTweet(9, "cbdefghik"));
        System.out.println(tweeter.postTweet(1, "iloveli"));
        tweeter.unfollow(5, 4);
        tweeter.follow(2, 10);
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(5, "ikisacbde"));
        tweeter.follow(14, 2);
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(8, "ntcode li"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(14, "ntcode"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(7, "lintco"));
        System.out.println(tweeter.postTweet(2, "efghi"));
        System.out.println(tweeter.postTweet(11, " love lin"));
        tweeter.follow(3, 12);
        tweeter.unfollow(9, 13);
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(9, "ntcod"));
        tweeter.follow(7, 15);
        tweeter.follow(16, 1);
        System.out.println(tweeter.postTweet(2, "ntcodeac"));
        System.out.println(tweeter.postTweet(9, "elintcodea"));
        tweeter.follow(14, 9);
        System.out.println(tweeter.postTweet(16, "ntcodeac"));
        System.out.println(tweeter.postTweet(6, "iklmnlint"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(4, "e lintco"));
        tweeter.unfollow(12, 13);
        tweeter.follow(5, 13);
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(4, "ode isbest"));
        System.out.println(tweeter.postTweet(8, "besti lov"));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.follow(6, 11); // stop here
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(4, "lintcodel"));
        System.out.println(tweeter.postTweet(10, "lintcod"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(12, "intco"));
        System.out.println(tweeter.getNewsFeed(12));
        tweeter.follow(16, 9);
        tweeter.follow(2, 5);
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.follow(6, 9);
        tweeter.follow(15, 4);
        tweeter.follow(11, 8);
        System.out.println(tweeter.postTweet(8, "kbest"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(12));
        tweeter.unfollow(13, 2);
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(5));
        tweeter.follow(11, 4);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(12, "cbdefghiki"));
        tweeter.follow(13, 8);
        System.out.println(tweeter.postTweet(16, "codeacbd"));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getTimeline(11));
        tweeter.follow(12, 15);
        tweeter.follow(6, 4);
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(13, "intcodei"));
        tweeter.follow(8, 1);
        tweeter.follow(13, 6);
        tweeter.follow(1, 6);
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(12, "i love"));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(2, " lintcode"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(12, "lintcod"));
        tweeter.unfollow(1, 14);
        tweeter.unfollow(3, 16);
        System.out.println(tweeter.postTweet(8, " love lin"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(13, "sacbdefgh"));
        tweeter.follow(7, 12);
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getTimeline(7));
        tweeter.unfollow(11, 9);
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.follow(7, 2);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(4, "intcodea"));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(15, "klintco"));
        System.out.println(tweeter.postTweet(4, "fghiki"));
        System.out.println(tweeter.postTweet(10, "kbesti lov"));
        System.out.println(tweeter.postTweet(13, "velin"));
        System.out.println(tweeter.postTweet(6, "i lov"));
        System.out.println(tweeter.postTweet(1, "lintcodeac"));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.postTweet(7, "cbdefghi"));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(4)); // where it mismatches with solution
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(12, "ghiklmnli"));
        tweeter.follow(4, 5);
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.unfollow(6, 11);
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(3, "de is"));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.follow(7, 14);
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(4, "sbesti "));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(11, " loveli"));
        System.out.println(tweeter.postTweet(7, "efghikisac"));
        System.out.println(tweeter.postTweet(16, "iklmnl"));
        System.out.println(tweeter.postTweet(15, "hikisac"));
        System.out.println(tweeter.postTweet(1, "odelintc"));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(2, "codeacbdef"));
        tweeter.follow(7, 16);
        tweeter.follow(14, 10);
        tweeter.unfollow(9, 12);
        System.out.println(tweeter.postTweet(16, "acbdefgh"));
        System.out.println(tweeter.postTweet(14, "ntcode"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(1, "codeli"));
        System.out.println(tweeter.postTweet(7, "odeacb"));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.follow(14, 1);
        tweeter.follow(5, 16);
        System.out.println(tweeter.postTweet(11, "code isb"));
        System.out.println(tweeter.postTweet(8, "defghi"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(15, "ghikbesti "));
        tweeter.follow(5, 3);
        tweeter.follow(3, 8);
        System.out.println(tweeter.getTimeline(15));
        tweeter.follow(7, 6);
        tweeter.follow(6, 1);
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(14, "e lintc"));
        System.out.println(tweeter.postTweet(7, "eilov"));
        System.out.println(tweeter.postTweet(1, "tcodel"));
        tweeter.follow(12, 11);
        System.out.println(tweeter.getTimeline(11));
        tweeter.follow(3, 7);
        tweeter.follow(8, 4);
        System.out.println(tweeter.postTweet(8, "fghikb"));
        System.out.println(tweeter.postTweet(5, "defghiki"));
        tweeter.follow(12, 5);
        System.out.println(tweeter.getTimeline(9));
        tweeter.unfollow(10, 2);
        tweeter.follow(5, 1);
        System.out.println(tweeter.postTweet(14, "acbde"));
        System.out.println(tweeter.getTimeline(6));
        tweeter.follow(12, 10);
        System.out.println(tweeter.postTweet(15, "ntcod"));
        tweeter.follow(11, 6);
        System.out.println(tweeter.postTweet(5, "sbest"));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.follow(10, 4);
        tweeter.unfollow(10, 4);
        System.out.println(tweeter.postTweet(10, "ikbesti lo"));
        System.out.println(tweeter.getTimeline(2));
        tweeter.follow(1, 16);
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(15, "isbesti"));
        System.out.println(tweeter.postTweet(5, "ntcodeac"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(16, "intcodel"));
        System.out.println(tweeter.postTweet(8, "besti"));
        System.out.println(tweeter.postTweet(1, "lintc"));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.follow(4, 8);
        tweeter.unfollow(8, 1);
        System.out.println(tweeter.getTimeline(15));
        tweeter.unfollow(11, 8);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getTimeline(12));
        tweeter.follow(10, 7);
        System.out.println(tweeter.postTweet(16, "fghiklin"));
        System.out.println(tweeter.postTweet(7, "mnlint"));
        System.out.println(tweeter.postTweet(9, "efghik"));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(10, "intco"));
        tweeter.follow(8, 13);
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.postTweet(5, "intcodeli"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(10, "intcodeac"));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.postTweet(11, "intcode i"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(11, "lintcode"));
        System.out.println(tweeter.postTweet(6, "code isb"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(2, "ghikisac"));
        System.out.println(tweeter.getTimeline(6));
        tweeter.follow(4, 2);
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.postTweet(4, "odelint"));
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.postTweet(9, "ilove"));
        System.out.println(tweeter.postTweet(5, "code lintc"));
        System.out.println(tweeter.getTimeline(1));
        tweeter.follow(12, 3);
        tweeter.follow(2, 13);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.postTweet(2, "ode lintco"));
        System.out.println(tweeter.postTweet(4, "sti love "));
        System.out.println(tweeter.postTweet(3, "iklintco"));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.unfollow(7, 15);
        System.out.println(tweeter.postTweet(8, "defgh"));
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.follow(6, 13);
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.follow(10, 11);
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.follow(15, 3);
        System.out.println(tweeter.postTweet(6, "defghi"));
        tweeter.follow(10, 4);
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(14, "sbesti l"));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.postTweet(10, "intcodeac"));
        System.out.println(tweeter.postTweet(13, "ghiklmnli"));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(13, " isbesti "));
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(13, "defghi"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(5, "tcode"));
        System.out.println(tweeter.postTweet(4, "ve lintcod"));
        System.out.println(tweeter.postTweet(7, "ntcode l"));
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.follow(14, 4);
        System.out.println(tweeter.postTweet(16, "deilove"));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(16, "cbdefghi"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(7, "ilovelintc"));
        System.out.println(tweeter.postTweet(15, "love lin"));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.follow(12, 6);
        tweeter.unfollow(8, 4);
        tweeter.unfollow(6, 7);
        System.out.println(tweeter.postTweet(11, "fghik"));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.postTweet(1, "elintcode"));
        System.out.println(tweeter.postTweet(9, "ode i"));
        System.out.println(tweeter.postTweet(16, "de isbes"));
        tweeter.unfollow(16, 15);
        System.out.println(tweeter.getTimeline(1));
        tweeter.follow(2, 4);
        System.out.println(tweeter.postTweet(6, " lovelint"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(8, "ntcode li"));
        tweeter.unfollow(3, 1);
        System.out.println(tweeter.postTweet(8, "ntcode "));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(1, "ghikisac"));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(4, "ghikli"));
        System.out.println(tweeter.postTweet(16, "ghiklmnlin"));
        tweeter.follow(8, 7);
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.follow(10, 16);
        tweeter.unfollow(7, 8);
        System.out.println(tweeter.postTweet(1, "hikbe"));
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.follow(5, 7);
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(11, "lintco"));
        System.out.println(tweeter.postTweet(15, "bdefghi"));
        tweeter.unfollow(7, 12);
        tweeter.follow(12, 4);
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(1, " lovel"));
        tweeter.unfollow(16, 9);
        System.out.println(tweeter.getNewsFeed(10));
        tweeter.follow(7, 15);
        System.out.println(tweeter.postTweet(10, "ti loveli"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(15, "elintc"));
        System.out.println(tweeter.postTweet(3, "intcode"));
        System.out.println(tweeter.postTweet(11, "ghiklmnl"));
        System.out.println(tweeter.getTimeline(5));
        tweeter.follow(1, 14);
        tweeter.follow(8, 12);
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(3, "bdefghikbe"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.postTweet(7, "lintcode"));
        tweeter.follow(16, 6);
        System.out.println(tweeter.postTweet(12, "intcodeacb"));
        System.out.println(tweeter.postTweet(2, "intcodeil"));
        System.out.println(tweeter.postTweet(8, "ntcodeilov"));
        System.out.println(tweeter.postTweet(10, "tcode"));
        System.out.println(tweeter.postTweet(15, "lintcode"));
        tweeter.follow(4, 16);
        tweeter.unfollow(10, 7);
        tweeter.follow(9, 10);
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(11, "ikbes"));
        tweeter.unfollow(13, 5);
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(7, "code is"));
        System.out.println(tweeter.postTweet(10, "codelint"));
        System.out.println(tweeter.postTweet(8, "tcode isbe"));
        tweeter.follow(11, 14);
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(1, " lovel"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(10, "ikbesti "));
        System.out.println(tweeter.postTweet(10, "intcodeli"));
        tweeter.follow(8, 15);
        tweeter.unfollow(8, 7);
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(16, "lmnlintcod"));
        System.out.println(tweeter.postTweet(2, "efghikl"));
        tweeter.follow(5, 12);
        System.out.println(tweeter.postTweet(7, "deilove"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(4, "lmnlin"));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getNewsFeed(12));
        tweeter.follow(2, 3);
        tweeter.follow(12, 1);
        System.out.println(tweeter.postTweet(1, "intcodeacb"));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(13, "lintco"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getNewsFeed(7));
        tweeter.follow(7, 9);
        tweeter.follow(8, 16);
        tweeter.unfollow(5, 13);
        tweeter.follow(13, 7);
        System.out.println(tweeter.postTweet(7, "isbest"));
        System.out.println(tweeter.postTweet(13, "delint"));
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.unfollow(14, 1);
        System.out.println(tweeter.postTweet(8, "ntcodeacbd"));
        System.out.println(tweeter.postTweet(14, "intcode"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(7, "ode isbe"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(10, "intcode i"));
        tweeter.unfollow(5, 16);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getTimeline(6));
        tweeter.unfollow(10, 16);
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(10, "mnlintc"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(9, "fghik"));
        tweeter.follow(6, 10);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.postTweet(4, "klmnlint"));
        System.out.println(tweeter.postTweet(15, "kisacbd"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(2, "ghikbesti"));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(3, "deilovelin"));
        tweeter.follow(16, 2);
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(14, "oveli"));
        tweeter.follow(6, 3);
        tweeter.follow(15, 9);
        System.out.println(tweeter.postTweet(11, "code is"));
        System.out.println(tweeter.postTweet(14, "intcod"));
        System.out.println(tweeter.getTimeline(7));
        tweeter.follow(3, 2);
        System.out.println(tweeter.postTweet(12, "efghiklmn"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(7, "ntcode isb"));
        tweeter.unfollow(13, 6);
        System.out.println(tweeter.getTimeline(9));
        tweeter.follow(16, 5);
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(8, "delintco"));
        tweeter.follow(9, 12);
        System.out.println(tweeter.postTweet(5, "cbdefghi"));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.postTweet(11, "efghi"));
        System.out.println(tweeter.postTweet(11, "delint"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(4, "de isbest"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(2, "fghikbest"));
        System.out.println(tweeter.postTweet(12, "lintcode i"));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(9, "delintcode"));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.unfollow(2, 3);
        tweeter.unfollow(5, 15);
        tweeter.unfollow(11, 4);
        System.out.println(tweeter.postTweet(12, "efghiki"));
        tweeter.unfollow(5, 12);
        tweeter.follow(1, 5);
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(10, "odeacb"));
        System.out.println(tweeter.getNewsFeed(12));
        tweeter.follow(1, 8);
        tweeter.follow(7, 1);
        System.out.println(tweeter.getTimeline(13));
        tweeter.unfollow(7, 1);
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(7, "sbesti lo"));
        System.out.println(tweeter.postTweet(10, "odeilov"));
        System.out.println(tweeter.postTweet(12, "acbde"));
        tweeter.unfollow(7, 2);
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(13, "code "));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(6, "intcod"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.unfollow(4, 8);
        System.out.println(tweeter.postTweet(3, "lintcodeli"));
        tweeter.follow(4, 8);
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(5));
        tweeter.unfollow(1, 6);
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.postTweet(15, "ntcod"));
        System.out.println(tweeter.postTweet(1, "acbde"));
        System.out.println(tweeter.postTweet(5, "ode isbest"));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.unfollow(14, 12);
        tweeter.follow(4, 12);
        System.out.println(tweeter.postTweet(11, "lintco"));
        System.out.println(tweeter.postTweet(2, "lintcod"));
        System.out.println(tweeter.postTweet(8, "bdefghikis"));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.follow(15, 11);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(4));
        tweeter.unfollow(8, 13);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.unfollow(10, 8);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(8, "acbdef"));
        System.out.println(tweeter.postTweet(11, "ove li"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(4, "tcode isb"));
        tweeter.follow(10, 8);
        System.out.println(tweeter.postTweet(14, "iloveli"));
        tweeter.follow(16, 11);
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(2));
        tweeter.follow(3, 5);
        System.out.println(tweeter.postTweet(8, "lintcodea"));
        tweeter.follow(4, 15);
        System.out.println(tweeter.postTweet(11, "sbesti l"));
        tweeter.unfollow(5, 9);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(8, "hiklmnlin"));
        System.out.println(tweeter.getTimeline(15));
        tweeter.follow(9, 8);
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.follow(8, 5);
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(3, "ntcode isb"));
        System.out.println(tweeter.postTweet(13, "deiloveli"));
        System.out.println(tweeter.postTweet(11, "nlintco"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(1, "elintcode"));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(5, "isacbde"));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.follow(12, 14);
        System.out.println(tweeter.postTweet(5, "delintcode"));
        tweeter.follow(8, 13);
        System.out.println(tweeter.postTweet(15, "velintcod"));
        System.out.println(tweeter.postTweet(3, "ghiklm"));
        tweeter.follow(9, 1);
        tweeter.unfollow(7, 9);
        System.out.println(tweeter.postTweet(5, "hiklin"));
        System.out.println(tweeter.postTweet(16, "tcodea"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(12, "besti l"));
        System.out.println(tweeter.getNewsFeed(10));
        tweeter.follow(10, 13);
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.postTweet(2, "tcode lin"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(3, "klintc"));
        tweeter.follow(8, 3);
        System.out.println(tweeter.postTweet(6, "tcode l"));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(7, "efghik"));
        System.out.println(tweeter.postTweet(7, "de lintco"));
        System.out.println(tweeter.getNewsFeed(2));
        tweeter.follow(11, 8);
        tweeter.follow(14, 1);
        System.out.println(tweeter.postTweet(7, "acbdefghik"));
        System.out.println(tweeter.postTweet(15, "efghi"));
        System.out.println(tweeter.postTweet(1, "codelint"));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.follow(7, 4);
        System.out.println(tweeter.postTweet(2, "ode isbes"));
        System.out.println(tweeter.postTweet(2, "lintcodea"));
        System.out.println(tweeter.postTweet(13, "lintco"));
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.postTweet(2, "bdefg"));
        tweeter.follow(5, 16);
        System.out.println(tweeter.postTweet(11, "mnlintc"));
        tweeter.unfollow(15, 11);
        System.out.println(tweeter.postTweet(8, "iklintco"));
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.unfollow(8, 3);
        tweeter.follow(8, 4);
        tweeter.follow(14, 15);
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(11, "esti l"));
        System.out.println(tweeter.postTweet(2, "elintcode"));
        System.out.println(tweeter.postTweet(6, "tcodel"));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.postTweet(4, "velintcode"));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.postTweet(2, "besti lov"));
        tweeter.follow(9, 4);
        System.out.println(tweeter.postTweet(2, "ghikli"));
        System.out.println(tweeter.postTweet(16, "lintcod"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(11, "ntcode"));
        System.out.println(tweeter.postTweet(4, "bdefghik"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(5, "lintcodei"));
        System.out.println(tweeter.postTweet(12, "ode i"));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(15, "tcode lin"));
        tweeter.follow(10, 15);
        System.out.println(tweeter.postTweet(1, "odeil"));
        tweeter.follow(3, 14);
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.postTweet(10, "kbesti l"));
        System.out.println(tweeter.postTweet(15, "i love"));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(1, "besti l"));
        tweeter.unfollow(9, 4);
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(14, "ovelin"));
        tweeter.unfollow(3, 2);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(8, "tcodelin"));
        System.out.println(tweeter.postTweet(8, "ode i"));
        System.out.println(tweeter.getTimeline(13));
        tweeter.follow(3, 9);
        System.out.println(tweeter.postTweet(16, "cbdefghik"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.postTweet(13, "lintc"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(14, "ikbesti"));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.unfollow(4, 9);
        System.out.println(tweeter.postTweet(10, "ode lintco"));
        System.out.println(tweeter.postTweet(10, "efghikisac"));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.follow(15, 2);
        tweeter.unfollow(8, 12);
        System.out.println(tweeter.getTimeline(15));
        tweeter.unfollow(16, 5);
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(11, "ntcod"));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.follow(13, 2);
        tweeter.follow(14, 16);
        tweeter.unfollow(8, 4);
        System.out.println(tweeter.postTweet(2, "tcode "));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(2, "ntcode "));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(8));
        tweeter.follow(8, 1);
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(3, "ntcodelin"));
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.follow(9, 11);
        System.out.println(tweeter.postTweet(16, "lintcodei"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.postTweet(1, "ode is"));
        tweeter.follow(7, 8);
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.postTweet(7, "ti lo"));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.postTweet(8, "intcode"));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.postTweet(14, "efghikli"));
        tweeter.unfollow(14, 2);
        tweeter.follow(1, 4);
        tweeter.follow(13, 5);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(4, "code lint"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(9, "e isbesti "));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(2, "eacbdefghi"));
        System.out.println(tweeter.postTweet(8, "ntcode "));
        tweeter.unfollow(8, 13);
        System.out.println(tweeter.postTweet(15, " lintco"));
        System.out.println(tweeter.postTweet(8, "intcode"));
        System.out.println(tweeter.getTimeline(2));
        tweeter.follow(16, 15);
        tweeter.follow(5, 12);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(1, "klmnli"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(3, "bdefghiki"));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.follow(1, 2);
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.postTweet(3, "besti l"));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.postTweet(16, "odeli"));
        System.out.println(tweeter.postTweet(14, "kbesti lov"));
        System.out.println(tweeter.postTweet(15, "love l"));
        System.out.println(tweeter.postTweet(2, "deacbdefg"));
        System.out.println(tweeter.postTweet(5, "hiklint"));
        tweeter.follow(14, 8);
        System.out.println(tweeter.postTweet(14, "tcode i"));
        tweeter.unfollow(16, 1);
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(3, " love lin"));
        System.out.println(tweeter.postTweet(16, "bdefghik"));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.postTweet(3, "deacb"));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.postTweet(14, "esti "));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(10, "isacbdefgh"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(14, "e lintcod"));
        System.out.println(tweeter.postTweet(9, "lintc"));
        System.out.println(tweeter.postTweet(4, "hikbesti l"));
        System.out.println(tweeter.postTweet(4, "defgh"));
        System.out.println(tweeter.getTimeline(11));
        tweeter.follow(7, 11);
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.unfollow(16, 15);
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.postTweet(9, "codeacbd"));
        System.out.println(tweeter.postTweet(4, "deiloveli"));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.follow(10, 16);
        System.out.println(tweeter.postTweet(13, "odeli"));
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.follow(16, 5);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(16, "ode li"));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.follow(14, 5);
        System.out.println(tweeter.getNewsFeed(10));
        tweeter.unfollow(7, 8);
        tweeter.unfollow(4, 12);
        System.out.println(tweeter.postTweet(9, "ntcode i"));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.unfollow(15, 2);
        System.out.println(tweeter.postTweet(11, " isbesti l"));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getTimeline(4));
        tweeter.unfollow(11, 8);
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getTimeline(9));
        tweeter.follow(15, 7);
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.unfollow(6, 4);
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(2, "ntcodeli"));
        tweeter.follow(1, 3);
        System.out.println(tweeter.postTweet(16, "cbdefghikl"));
        tweeter.follow(15, 1);
        System.out.println(tweeter.postTweet(15, "delintcode"));
        System.out.println(tweeter.postTweet(5, "odelint"));
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.unfollow(11, 6);
        System.out.println(tweeter.postTweet(16, "delintcod"));
        tweeter.unfollow(9, 1);
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.postTweet(14, "lovelintco"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(9, "velintc"));
        System.out.println(tweeter.postTweet(6, "lintcodel"));
        System.out.println(tweeter.postTweet(13, "velin"));
        tweeter.follow(13, 11);
        System.out.println(tweeter.postTweet(1, "elintco"));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.unfollow(5, 7);
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(4));
        tweeter.follow(3, 13);
        System.out.println(tweeter.postTweet(9, "efghikisac"));
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.unfollow(16, 5);
        tweeter.unfollow(16, 12);
        System.out.println(tweeter.postTweet(8, "besti"));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.postTweet(11, "bdefgh"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(1, "de isbesti"));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.postTweet(7, "tcodel"));
        System.out.println(tweeter.getTimeline(9));
        tweeter.follow(9, 7);
        tweeter.follow(4, 11);
        System.out.println(tweeter.postTweet(16, "hiklmnlint"));
        System.out.println(tweeter.postTweet(16, "codeacbde"));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.postTweet(4, "lintcode"));
        System.out.println(tweeter.postTweet(10, "sacbdefgh"));
        System.out.println(tweeter.postTweet(9, "delintco"));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(13, "intcode i"));
        tweeter.follow(6, 5);
        System.out.println(tweeter.postTweet(7, "tcodeli"));
        System.out.println(tweeter.getNewsFeed(7));
        tweeter.unfollow(15, 5);
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.unfollow(15, 3);
        System.out.println(tweeter.postTweet(16, "ntcod"));
        System.out.println(tweeter.postTweet(15, "ntcodeacbd"));
        System.out.println(tweeter.getNewsFeed(8));
        tweeter.unfollow(8, 1);
        System.out.println(tweeter.postTweet(16, "hikisacb"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(1, "nlintcodel"));
        System.out.println(tweeter.postTweet(2, "odeilove"));
        System.out.println(tweeter.getNewsFeed(3));
        System.out.println(tweeter.postTweet(3, "e lintcod"));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(3, "e lintcode"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(1, "intco"));
        System.out.println(tweeter.postTweet(1, "deacb"));
        System.out.println(tweeter.postTweet(12, "fghikli"));
        System.out.println(tweeter.getNewsFeed(5));
        tweeter.follow(11, 9);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(11, "intco"));
        System.out.println(tweeter.postTweet(4, "ve lint"));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.postTweet(14, "iklintco"));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(10, "tcodea"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getNewsFeed(3));
        tweeter.follow(14, 2);
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.unfollow(4, 6);
        System.out.println(tweeter.getTimeline(16));
        tweeter.unfollow(12, 14);
        System.out.println(tweeter.postTweet(13, "odelintco"));
        System.out.println(tweeter.postTweet(11, "ode lint"));
        System.out.println(tweeter.postTweet(12, "ovelin"));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.postTweet(14, "defghikl"));
        System.out.println(tweeter.postTweet(1, "fghikbest"));
        System.out.println(tweeter.getTimeline(8));
        tweeter.follow(2, 1);
        tweeter.unfollow(1, 9);
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(5, "besti love"));
        tweeter.follow(2, 12);
        tweeter.follow(8, 6);
        tweeter.follow(16, 9);
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.unfollow(3, 5);
        tweeter.unfollow(3, 13);
        System.out.println(tweeter.postTweet(9, "ntcode l"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.unfollow(4, 10);
        System.out.println(tweeter.postTweet(14, "e lintcod"));
        System.out.println(tweeter.postTweet(10, "odelint"));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(10));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.postTweet(1, "deacbdef"));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.postTweet(5, "tcode is"));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.getNewsFeed(13));
        tweeter.follow(6, 7);
        System.out.println(tweeter.postTweet(1, "hiklm"));
        tweeter.unfollow(1, 8);
        tweeter.follow(12, 13);
        System.out.println(tweeter.postTweet(12, "sti lo"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(11, "acbdefgh"));
        System.out.println(tweeter.postTweet(4, "bdefghik"));
        tweeter.unfollow(12, 1);
        tweeter.follow(12, 8);
        System.out.println(tweeter.getTimeline(16));
        tweeter.unfollow(7, 16);
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getTimeline(2));
        tweeter.follow(2, 15);
        System.out.println(tweeter.postTweet(3, "odelintc"));
        System.out.println(tweeter.postTweet(6, "hiklm"));
        System.out.println(tweeter.postTweet(5, "fghikli"));
        tweeter.follow(10, 3);
        tweeter.follow(9, 16);
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.getNewsFeed(15));
        System.out.println(tweeter.postTweet(12, "elintcode"));
        System.out.println(tweeter.getTimeline(12));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getNewsFeed(16));
        tweeter.unfollow(1, 2);
        System.out.println(tweeter.postTweet(16, "efghik"));
        tweeter.follow(15, 14);
        tweeter.follow(14, 13);
        tweeter.unfollow(11, 9);
        System.out.println(tweeter.postTweet(15, "besti love"));
        System.out.println(tweeter.postTweet(8, "nlintcode"));
        System.out.println(tweeter.postTweet(9, "lintc"));
        System.out.println(tweeter.postTweet(1, "bdefghikl"));
        tweeter.unfollow(3, 8);
        System.out.println(tweeter.getTimeline(8));
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.unfollow(10, 4);
        System.out.println(tweeter.postTweet(9, "ode lin"));
        System.out.println(tweeter.postTweet(15, "intcodeilo"));
        System.out.println(tweeter.postTweet(9, "elintc"));
        tweeter.follow(15, 2);
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(5));
        System.out.println(tweeter.postTweet(5, " love lin"));
        System.out.println(tweeter.getNewsFeed(12));
        tweeter.follow(7, 12);
        System.out.println(tweeter.postTweet(4, "hikbest"));
        tweeter.unfollow(1, 10);
        System.out.println(tweeter.getNewsFeed(8));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.follow(10, 5);
        System.out.println(tweeter.postTweet(7, "sti lov"));
        System.out.println(tweeter.postTweet(7, "ve lintc"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(8, "i love"));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.postTweet(16, "elint"));
        System.out.println(tweeter.postTweet(15, "intcode l"));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.postTweet(6, "elintcode"));
        System.out.println(tweeter.postTweet(15, "efghiklmnl"));
        System.out.println(tweeter.postTweet(16, "tcodeacb"));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getTimeline(5));
        System.out.println(tweeter.getTimeline(16));
        System.out.println(tweeter.postTweet(6, "odelin"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getNewsFeed(4));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.getTimeline(2));
        System.out.println(tweeter.getTimeline(16));
        tweeter.follow(7, 2);
        System.out.println(tweeter.postTweet(8, "ode isbe"));
        tweeter.unfollow(4, 11);
        System.out.println(tweeter.postTweet(9, "elintcode"));
        System.out.println(tweeter.postTweet(7, "elintcode"));
        System.out.println(tweeter.getNewsFeed(16));
        tweeter.follow(10, 12);
        System.out.println(tweeter.postTweet(12, "ikbes"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.unfollow(2, 1);
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.follow(11, 1);
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getTimeline(7));
        System.out.println(tweeter.postTweet(13, "i love lin"));
        System.out.println(tweeter.postTweet(5, "odeilove"));
        System.out.println(tweeter.postTweet(3, "eacbde"));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(6, "ikisacbde"));
        tweeter.unfollow(4, 16);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(13, " lintcode"));
        System.out.println(tweeter.getTimeline(3));
        System.out.println(tweeter.postTweet(5, "velint"));
        System.out.println(tweeter.postTweet(15, "odelintcod"));
        System.out.println(tweeter.postTweet(4, "de isb"));
        System.out.println(tweeter.postTweet(2, "ghiklin"));
        System.out.println(tweeter.postTweet(15, "bdefghi"));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.postTweet(8, "bdefg"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(15));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getTimeline(9));
        System.out.println(tweeter.postTweet(10, "de is"));
        System.out.println(tweeter.postTweet(2, "bdefghiklm"));
        System.out.println(tweeter.postTweet(12, " lintco"));
        tweeter.follow(5, 14);
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.follow(14, 6);
        System.out.println(tweeter.postTweet(5, "elintc"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(9, "deacbdefgh"));
        System.out.println(tweeter.postTweet(5, "ghikis"));
        System.out.println(tweeter.getTimeline(11));
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.getNewsFeed(9));
        tweeter.unfollow(15, 8);
        System.out.println(tweeter.getNewsFeed(10));
        System.out.println(tweeter.postTweet(2, "bdefghikl"));
        System.out.println(tweeter.postTweet(16, "ilovelintc"));
        System.out.println(tweeter.postTweet(10, "efghiklmnl"));
        System.out.println(tweeter.postTweet(7, "lintcod"));
        System.out.println(tweeter.getNewsFeed(2));
        System.out.println(tweeter.postTweet(8, "iklmnli"));
        System.out.println(tweeter.postTweet(3, "acbdefgh"));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.postTweet(1, "intcode is"));
        System.out.println(tweeter.getNewsFeed(6));
        System.out.println(tweeter.getTimeline(13));
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(13));
        System.out.println(tweeter.postTweet(15, "tcodelin"));
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.postTweet(9, "delin"));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.unfollow(13, 5);
        tweeter.follow(1, 2);
        tweeter.follow(8, 2);
        System.out.println(tweeter.getNewsFeed(1));
        System.out.println(tweeter.postTweet(10, "klint"));
        System.out.println(tweeter.postTweet(10, "efghikb"));
        System.out.println(tweeter.getNewsFeed(9));
        System.out.println(tweeter.postTweet(5, "code i"));
        tweeter.follow(2, 1);
        System.out.println(tweeter.postTweet(11, " isbesti "));
        tweeter.unfollow(1, 5);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(6));
        tweeter.unfollow(4, 13);
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.getNewsFeed(1));
        tweeter.unfollow(16, 2);
        System.out.println(tweeter.postTweet(11, "isbesti "));
        System.out.println(tweeter.getTimeline(1));
        System.out.println(tweeter.postTweet(4, "besti"));
        tweeter.follow(3, 2);
        System.out.println(tweeter.postTweet(16, "fghikbest"));
        System.out.println(tweeter.postTweet(15, "ntcod"));
        tweeter.unfollow(11, 1);
        System.out.println(tweeter.postTweet(3, "fghikis"));
        System.out.println(tweeter.getNewsFeed(7));
        tweeter.follow(14, 3);
        System.out.println(tweeter.postTweet(13, "velin"));
        System.out.println(tweeter.postTweet(11, "odelint"));
        tweeter.follow(8, 13);
        System.out.println(tweeter.postTweet(6, "e isbesti "));
        System.out.println(tweeter.getTimeline(6));
        System.out.println(tweeter.getNewsFeed(7));
        tweeter.follow(13, 15);
        System.out.println(tweeter.getNewsFeed(11));
        tweeter.follow(4, 9);
        System.out.println(tweeter.getNewsFeed(14));
        System.out.println(tweeter.getNewsFeed(11));
        System.out.println(tweeter.getNewsFeed(16));
        System.out.println(tweeter.getTimeline(4));
        System.out.println(tweeter.postTweet(3, "odelin"));
        System.out.println(tweeter.getNewsFeed(15));
        tweeter.follow(13, 10);
        System.out.println(tweeter.postTweet(6, "hikbesti l"));
        System.out.println(tweeter.postTweet(6, "tcodelint"));
        System.out.println(tweeter.getNewsFeed(12));
        tweeter.follow(10, 6);
        tweeter.follow(4, 11);
        System.out.println(tweeter.postTweet(9, "lintcodel"));
        tweeter.follow(16, 14);
        tweeter.unfollow(14, 16);
        System.out.println(tweeter.postTweet(14, "e lintc"));
        System.out.println(tweeter.getNewsFeed(12));
        System.out.println(tweeter.getNewsFeed(7));
        System.out.println(tweeter.getTimeline(14));
        System.out.println(tweeter.getNewsFeed(4));
        tweeter.follow(9, 6);
        System.out.println(tweeter.getNewsFeed(14));
        tweeter.unfollow(14, 2);
        System.out.println(tweeter.postTweet(15, "ti love l"));
        System.out.println(tweeter.postTweet(12, "ntcodeilo"));
        System.out.println(tweeter.getNewsFeed(7));

    }
}